Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/precise32"
	config.vm.network :forwarded_port, guest: 8080, host: 9090
	config.vm.provision "puppet" do |puppet|
		puppet.manifest_file = "web.pp"
	end
end